server:
  port: 8085
spring:
  application:
    name: factory-service
    kafka:
      request: "ORDER_FACTORY_TOPIC"
      response: "FACTORY_ORDER_TOPIC"
  kafka:
    consumer:
      group-id: "factory-group"
      bootstrap-servers: "localhost:9092"
      client-id: "factory-consumer"
      auto-offset-reset: earliest

    producer:
      bootstrap-servers: "127.0.0.1:9092"
      client-id: "factory-producer"


  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    show-sql: true
  jmx:
    enabled: true

  eureka:
    client:
      registerWithEureka: false
      fetchRegistry: false
      service-url:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: metrics, health, logfile
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  file:
    name: factory-service.log

job:
  sender:
    cron: "*/10 * * * * *"
  process:
    cron: "*/10 * * * * *"
